### ISSUE TITLE
test/websocket_test.dart: diffBookDepth fails, maybe allBookTicker?

### ISSUE THREAD

**Issue by lukepighetti** [lukepighetti/binance-dart#4]
```
00:09 +19 -1: test/websocket_test.dart: allBookTicker [E]                                                                                                                                              
  SocketException: Reading from a closed socket
  dart:_http                                WebSocket.connect
  package:web_socket_channel/io.dart 57:55  new IOWebSocketChannel.connect
  package:binance/src/websocket.dart 7:68   BinanceWebsocket._public
  package:binance/src/websocket.dart 76:21  BinanceWebsocket.allBookTicker
  test/websocket_test.dart 59:36            main.<fn>
  
  This test failed after it had already completed. Make sure to use [expectAsync]
```

This appears to have been introduced by https://github.com/lukepighetti/binance-dart/pull/2 which is on pub as `1.0.3`

@ChunYoLin can you please investigate?

**Comment by ChunYoLin** [comment]
OK,let me try to fix it.

**Comment by ChunYoLin** [comment]
Hi @lukepighetti , can I call you Luke? :) 

I think the problem might come from the binance server,
because sometimes it works sometimes it doesn't,
so I think maybe we can put a try catch block on IOWebSocketChannel.connect at _public?
I am not very familiar with dart asynchronous programming, so I might be wrong :(

**Comment by lukepighetti** [comment]
Let's just put a `@Skip('Flakey test, works in practice')` decorator on it and call it good for now then

**Comment by lukepighetti** [comment]
Test suppressed by https://github.com/lukepighetti/binance-dart/pull/5
